// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4Zl8qVyYYiNoepJN4Ojx5d2DBOvARxgw',
    appId: '1:828690638638:web:9664ae1d890d9117a0fcbf',
    messagingSenderId: '828690638638',
    projectId: 'medg-a4a69',
    authDomain: 'medg-a4a69.firebaseapp.com',
    storageBucket: 'medg-a4a69.appspot.com',
    measurementId: 'G-TKEN9J3QBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb7qgo-doHtJiNNRi3wIGLZmM1ncKAq7o',
    appId: '1:828690638638:android:c10cec405aef1f11a0fcbf',
    messagingSenderId: '828690638638',
    projectId: 'medg-a4a69',
    storageBucket: 'medg-a4a69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuMfUXABCcTmBrv5NTp0PEUtVb_G1L-Lc',
    appId: '1:828690638638:ios:f4aa2066370af0a3a0fcbf',
    messagingSenderId: '828690638638',
    projectId: 'medg-a4a69',
    storageBucket: 'medg-a4a69.appspot.com',
    iosBundleId: 'com.example.medgExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuMfUXABCcTmBrv5NTp0PEUtVb_G1L-Lc',
    appId: '1:828690638638:ios:d636e29d54d6ed5da0fcbf',
    messagingSenderId: '828690638638',
    projectId: 'medg-a4a69',
    storageBucket: 'medg-a4a69.appspot.com',
    iosBundleId: 'com.example.medgExam.RunnerTests',
  );
}
